spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_drive
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  data:
    mongodb:
      uri: mongodb://localhost:27017/cloud_drive
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: file-service-group
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
